# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 174)
        MainWindow.setMinimumSize(QtCore.QSize(435, 174))
        MainWindow.setMaximumSize(QtCore.QSize(435, 174))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(20, 30, 113, 20))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(30, 50, 71, 16))
        self.label_name.setObjectName("label_name")
        self.pushButton_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(130, 110, 81, 21))
        self.pushButton_add.setObjectName("pushButton_add")
        self.lineEdit_score = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_score.setGeometry(QtCore.QRect(20, 70, 113, 20))
        self.lineEdit_score.setObjectName("lineEdit_score")
        self.label_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(30, 90, 47, 13))
        self.label_score.setObjectName("label_score")
        self.listWidget_grades = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget_grades.setGeometry(QtCore.QRect(140, 10, 211, 91))
        self.listWidget_grades.setObjectName("listWidget_grades")
        self.pushButton_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_edit.setGeometry(QtCore.QRect(220, 110, 75, 23))
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.pushButton_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(300, 110, 75, 23))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(370, 10, 51, 41))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_load = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_load.setGeometry(QtCore.QRect(370, 60, 51, 41))
        self.pushButton_load.setObjectName("pushButton_load")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 435, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.pushButton_add.setText(_translate("MainWindow", "Add"))
        self.label_score.setText(_translate("MainWindow", "Score"))
        self.pushButton_edit.setText(_translate("MainWindow", "Edit"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete"))
        self.pushButton_save.setText(_translate("MainWindow", "SAVE"))
        self.pushButton_load.setText(_translate("MainWindow", "LOAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
